Linting github actions.

diff --git a/tasks/test.yml b/tasks/test.yml
--- a/tasks/test.yml
+++ b/tasks/test.yml
@@ -19,7 +19,7 @@ vars:
 tasks:
   static:
     desc: Runs all static tests
-    deps: [security, lint, phpstan, phpunit:static, phpcs]
+    deps: [security, lint, phpstan, phpunit:static, phpcs, lint:github-actions]
   functional:
     desc: Runs all tests that require a bootstrapped Drupal site
     deps: [config, phpunit:functional, nightwatch]
@@ -77,6 +77,55 @@ tasks:
         elif [ -f ".eslintrc.json" ] && [ -f "package-lock.json" ]; then
           npm run eslint .
         fi
+  lint:github-actions:install:
+    desc: Installs action-validator for linting github-actions.
+    interactive: true
+    cmds:
+      - |
+        PACKAGES="@action-validator/core @action-validator/cli"
+        if [ ! -f "package.json" ]; then
+          echo -n "No package.json exists, would you like to use yarn1, npm, or yarn? "
+          read -r PACKAGE_MANAGER
+          if [ "$PACKAGE_MANAGER" == "npm" ]; then
+            if [ "$IS_DDEV_PROJECT" == "true" ]; then
+              sudo npm update -g
+            fi
+            npm init -y
+            npm install -g $PACKAGES --save-dev
+          elif [ "$PACKAGE_MANAGER" == "yarn1" ]; then
+            yarn set version classic
+            yarn init -y
+            yarn add $PACKAGES --dev
+          elif [ "$PACKAGE_MANAGER" == "yarn" ]; then
+            yarn set version berry
+            yarn init
+            yarn global add $PACKAGES --dev
+          else
+            echo "Sorry I'm not aware of that package manager. Please first init package.json with it yourself manually."
+          fi
+        else
+          if [ -f "package-lock.json" ]; then
+            npm install -g $PACKAGES --save-dev
+          elif [ -f "yarn.lock" ]; then
+            yarn global add $PACKAGES --dev
+          else
+            echo "package.json found but unable to figure out which package manager is in use"
+            echo "Please manually install $PACKAGES"
+            exit 1;
+          fi
+        fi
+  lint:github-actions:test:
+    desc: Run lint on github-actions to ensure they are valid.
+    cmds:
+      - |
+        find .github/workflows .github/actions -type f \( -iname '*.yaml' -o -iname '*.yml' \)
+  lint:github-actions:
+    desc: Run lint on github-actions to ensure they are valid.
+    deps: [lint:github-actions:install]
+    cmds:
+      - |
+        find .github/workflows .github/actions -type f \( -iname '*.yaml' -o -iname '*.yml' \) \
+          | xargs -n1 action-validator
   config:
     desc: "Verifies that exported config matches the config in Drupal. Run with format=short to skip showing the full table of diffs."
     # @todo JUnit output
